DEFINE INDEX_TBS = &&1

CREATE TABLE SEASON (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    NAME varchar2(100),
    YEAR NUMBER,
    CONSTRAINT PK_SEASON PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TBS
);