ALTER TABLE SEASON_EVENT ADD CONSTRAINT FK_SEASON_ID_season_id FOREIGN KEY(SEASON_ID)
REFERENCES SEASON (ID) ON DELETE CASCADE;

ALTER TABLE SEASON_EVENT ADD CONSTRAINT FK_SEASON_EVENT_event_id FOREIGN KEY(EVENT_ID)
REFERENCES EVENT (ID) ON DELETE CASCADE;

ALTER TABLE SEASON_EVENT ADD CONSTRAINT FK_SEASON_EVENT_track_id FOREIGN KEY(TRACK_ID)
REFERENCES TRACK (ID) ON DELETE CASCADE;

ALTER TABLE TEAM_STATISTIC ADD CONSTRAINT FK_TEAM_STATISTIC_season_id FOREIGN KEY(SEASON_ID)
REFERENCES SEASON (ID) ON DELETE CASCADE;

ALTER TABLE TEAM_STATISTIC ADD CONSTRAINT FK_TEAM_STATISTIC_team_id FOREIGN KEY(TEAM_ID)
REFERENCES TEAM (ID) ON DELETE CASCADE;

ALTER TABLE DRIVER_STATISTIC ADD CONSTRAINT FK_DRIVER_STATISTIC_season_id FOREIGN KEY(SEASON_ID)
REFERENCES SEASON (ID) ON DELETE CASCADE;

ALTER TABLE DRIVER_STATISTIC ADD CONSTRAINT FK_DRIVER_STATISTIC_driver_id FOREIGN KEY(DRIVER_ID)
REFERENCES DRIVER (ID) ON DELETE CASCADE;

ALTER TABLE DRIVER_STATISTIC ADD CONSTRAINT FK_DRIVER_STATISTIC_team_id FOREIGN KEY(TEAM_ID)
REFERENCES TEAM (ID) ON DELETE CASCADE;

ALTER TABLE EVENT_RESULT ADD CONSTRAINT FK_EVENT_RESULT_season_id FOREIGN KEY(SEASON_ID)
REFERENCES SEASON (ID) ON DELETE CASCADE;

ALTER TABLE EVENT_RESULT ADD CONSTRAINT FK_EVENT_RESULT_event_id FOREIGN KEY(EVENT_ID)
REFERENCES EVENT (ID) ON DELETE CASCADE;

ALTER TABLE EVENT_RESULT ADD CONSTRAINT FK_EVENT_RESULT_driver_id FOREIGN KEY(DRIVER_ID)
REFERENCES DRIVER (ID) ON DELETE CASCADE;