ALTER TABLE "SEASON_EVENT" ADD CONSTRAINT "fk_SEASON_EVENT_season_id" FOREIGN KEY("season_id")
REFERENCES "SEASON" ("id");

ALTER TABLE "SEASON_EVENT" ADD CONSTRAINT "fk_SEASON_EVENT_event_id" FOREIGN KEY("event_id")
REFERENCES "EVENT" ("id");

ALTER TABLE "SEASON_EVENT" ADD CONSTRAINT "fk_SEASON_EVENT_track_id" FOREIGN KEY("track_id")
REFERENCES "TRACK" ("id");

ALTER TABLE "TEAM_STATISTIC" ADD CONSTRAINT "fk_TEAM_STATISTIC_season_id" FOREIGN KEY("season_id")
REFERENCES "SEASON" ("id");

ALTER TABLE "TEAM_STATISTIC" ADD CONSTRAINT "fk_TEAM_STATISTIC_team_id" FOREIGN KEY("team_id")
REFERENCES "TEAM" ("id");

ALTER TABLE "DRIVER_STATISTIC" ADD CONSTRAINT "fk_DRIVER_STATISTIC_season_id" FOREIGN KEY("season_id")
REFERENCES "SEASON" ("id");

ALTER TABLE "DRIVER_STATISTIC" ADD CONSTRAINT "fk_DRIVER_STATISTIC_driver_id" FOREIGN KEY("driver_id")
REFERENCES "DRIVER" ("id");

ALTER TABLE "DRIVER_STATISTIC" ADD CONSTRAINT "fk_DRIVER_STATISTIC_team_id" FOREIGN KEY("team_id")
REFERENCES "TEAM" ("id");

ALTER TABLE "EVENT_RESULT" ADD CONSTRAINT "fk_EVENT_RESULT_season_id" FOREIGN KEY("season_id")
REFERENCES "SEASON" ("id");

ALTER TABLE "EVENT_RESULT" ADD CONSTRAINT "fk_EVENT_RESULT_event_id" FOREIGN KEY("event_id")
REFERENCES "EVENT" ("id");

ALTER TABLE "EVENT_RESULT" ADD CONSTRAINT "fk_EVENT_RESULT_driver_id" FOREIGN KEY("driver_id")
REFERENCES "DRIVER" ("id");