DEFINE INDEX_TBS = &&1

CREATE TABLE EVENT (
    ID int GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    NAME varchar2(100),
    EVENT_DATE DATE,
    CONSTRAINT PK_EVENT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TBS
);

COMMENT ON COLUMN EVENT.ID IS 'Unique value, serves as the primary key for the table';
COMMENT ON COLUMN EVENT.NAME IS 'NAME of the event';
COMMENT ON COLUMN EVENT.EVENT_DATE IS 'Date of the event';