DEFINE INDEX_TBS = &&1

CREATE TABLE TEAM_STATISTIC (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    SEASON_ID NUMBER,
    TEAM_ID NUMBER,
    NUM_OF_WINS NUMBER,
    CONSTRAINT PK_TEAM_STATISTIC PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TBS
);