SET SERVEROUTPUT ON SIZE 30000;
DECLARE
    NUM NUMBER;    
BEGIN
    SELECT COUNT(ID) INTO NUM FROM DRIVER;
    DBMS_OUTPUT.PUT_LINE('DRIVER, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM DRIVER_STATISTIC;
    DBMS_OUTPUT.PUT_LINE('DRIVER_STATISTIC, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM EVENT;
    DBMS_OUTPUT.PUT_LINE('EVENT, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM EVENT_RESULT;
    DBMS_OUTPUT.PUT_LINE('EVENT_RESULT, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM SEASON;
    DBMS_OUTPUT.PUT_LINE('SEASON, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM SEASON_EVENT;
    DBMS_OUTPUT.PUT_LINE('SEASON_EVENT, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM TEAM;
    DBMS_OUTPUT.PUT_LINE('TEAM, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM TEAM_STATISTIC;
    DBMS_OUTPUT.PUT_LINE('TEAM_STATISTIC, NUMBERS OF ROWS: ' || NUM);
    
    SELECT COUNT(ID) INTO NUM FROM TRACK;
    DBMS_OUTPUT.PUT_LINE('TRACK, NUMBERS OF ROWS: ' || NUM);
END;