CREATE TABLE DATA_TABLE ( 
    SEASON VARCHAR2(26),
    EVENT_DATE DATE NOT NULL,
    EVENT VARCHAR2(26),
    CIRCUIT VARCHAR2(128),
    DRIVER VARCHAR2(26),
    CONSTRUCTOR VARCHAR2(26),
    LAPS NUMBER(38),
    TIME VARCHAR2(26),
    POINTS NUMBER(38),
    START_DRIVER_PLACE NUMBER(38),
    POLE_POSITION VARCHAR2(26),
    WINNER VARCHAR2(26),
    DRIVER_WINS NUMBER(38),
    CONSTRUCTOR_WINS NUMBER(38)
);
