--INSERT SEASON 
MERGE INTO SEASON 
    USING ( 
        SELECT DISTINCT SEASON 
        FROM DATA_TABLE) T1
    ON (SEASON.NAME = T1.SEASON)
WHEN NOT MATCHED THEN
    INSERT (NAME, YEAR) VALUES(T1.SEASON, CAST(SUBSTR(T1.SEASON,1,4) AS NUMBER));


--INSERT EVENTS
MERGE INTO EVENT
    USING( 
    SELECT DISTINCT 
    EVENT,
    EVENT_DATE
    FROM DATA_TABLE) T2
    ON (EVENT.NAME = T2.EVENT)
WHEN NOT MATCHED THEN
    INSERT (NAME, EVENT_DATE)
    VALUES(T2.EVENT, T2.EVENT_DATE);


--INSERT TRACKS
MERGE INTO TRACK
    USING(
        SELECT DISTINCT CIRCUIT
        FROM DATA_TABLE
        ) T3
    ON (TRACK.NAME = T3.CIRCUIT)
WHEN NOT MATCHED THEN
    INSERT(NAME,LENGTH,LATITUDE,LONGITUDE,COUNTRY,CITY)
    VALUES(T3.CIRCUIT,0,0,0,0,0); 


--INSERT TEAMS
MERGE INTO TEAM
    USING(
        SELECT DISTINCT 
        CONSTRUCTOR
        FROM DATA_TABLE
        ) T4
    ON (TEAM.NAME = T4.CONSTRUCTOR)
WHEN NOT MATCHED THEN
    INSERT(NAME, COUNTRY)
    VALUES(T4.CONSTRUCTOR,'');


--INSERT DRIVER
MERGE INTO DRIVER
    USING(
        SELECT DISTINCT 
        DRIVER, DRIVER_WINS
        FROM DATA_TABLE
        ) T5
    ON(DRIVER.NAME = T5.DRIVER)
WHEN NOT MATCHED THEN
    INSERT (NAME, NUM_OF_POLES,NUM_OF_EVENTS, NUM_OF_SEASONS)
    VALUES(T5.DRIVER,T5.DRIVER_WINS, 0, 0);


--insert season_event
MERGE INTO SEASON_EVENT
    USING (
        SELECT DISTINCT 
        SEASON.ID S_ID,
        EVENT.ID E_ID,
        TRACK.ID T_ID
        FROM DATA_TABLE DT1
        LEFT JOIN SEASON
        ON SEASON.NAME = DT1.SEASON
        LEFT JOIN TRACK
        ON TRACK.NAME = DT1.CIRCUIT
        LEFT JOIN EVENT
        ON EVENT.NAME = DT1.EVENT
        WHERE EXTRACT(YEAR FROM EVENT.EVENT_DATE) = SEASON.YEAR
        ) T1
    ON(SEASON_EVENT.SEASON_ID = T1.S_ID AND SEASON_EVENT.EVENT_ID = E_ID AND SEASON_EVENT.TRACK_ID = T_ID)
WHEN NOT MATCHED THEN
    INSERT(SEASON_EVENT.SEASON_ID, SEASON_EVENT.EVENT_ID, SEASON_EVENT.TRACK_ID)
    VALUES(T1.S_ID, T1.E_ID, T1.T_ID);

--INSERT TEAM_STAT
MERGE INTO TEAM_STATISTIC
    USING(
        SELECT DISTINCT
        SEASON.ID S_ID,
        TEAM.ID T_ID,
        CONSTRUCTOR_WINS C_WINS
        FROM DATA_TABLE DT1
        LEFT JOIN SEASON
        ON SEASON.NAME = DT1.SEASON
        LEFT JOIN TEAM
        ON TEAM.NAME = DT1.CONSTRUCTOR
        ) T1
    ON(TEAM_STATISTIC.SEASON_ID = T1.S_ID AND TEAM_STATISTIC.TEAM_ID = T1.T_ID)
WHEN NOT MATCHED THEN
    INSERT(TEAM_STATISTIC.SEASON_ID, TEAM_STATISTIC.TEAM_ID, TEAM_STATISTIC.NUM_OF_WINS)
    VALUES(T1.S_ID,T1.T_ID,T1.C_WINS);


--INSERT DRIVER_STAT
MERGE INTO DRIVER_STATISTIC
    USING(
        SELECT DISTINCT
        SEASON.ID S_ID,
        DRIVER.ID D_ID,
        TEAM.ID T_ID,
        DRIVER_WINS D_WINS
        FROM DATA_TABLE DT1
        LEFT JOIN SEASON
        ON SEASON.NAME = DT1.SEASON
        LEFT JOIN DRIVER
        ON DRIVER.NAME = DT1.DRIVER
        LEFT JOIN TEAM
        ON TEAM.NAME = DT1.CONSTRUCTOR
        )T1
    ON(DRIVER_STATISTIC.SEASON_ID = T1.S_ID AND DRIVER_STATISTIC.DRIVER_ID = T1.D_ID)
WHEN NOT MATCHED THEN
    INSERT(DRIVER_STATISTIC.SEASON_ID, DRIVER_STATISTIC.DRIVER_ID,DRIVER_STATISTIC.TEAM_ID,DRIVER_STATISTIC.EVENT_WINS)
    VALUES(T1.S_ID,T1.D_ID,T1.T_ID,T1.D_WINS);


--event result
MERGE INTO EVENT_RESULT
    USING(
        SELECT DISTINCT
        SEASON.ID S_ID,
        EVENT.ID E_ID,
        TRACK.ID TRACK_ID,
        DRIVER.ID D_ID,
        TEAM.ID TEAM_ID,
        LAPS,
        TIME,
        POINTS,
        START_DRIVER_PLACE,
        DRIVER.ID POLE_POSITION,
        DRIVER.ID WINNER
        FROM DATA_TABLE DT1
        LEFT JOIN SEASON
        ON SEASON.NAME = DT1.SEASON
        LEFT JOIN TRACK
        ON TRACK.NAME = DT1.CIRCUIT
        LEFT JOIN DRIVER
        ON DRIVER.NAME = DT1.DRIVER
        LEFT JOIN TEAM
        ON TEAM.NAME = DT1.CONSTRUCTOR
        LEFT JOIN EVENT
        ON EVENT.NAME = DT1.EVENT
        WHERE EXTRACT(YEAR FROM EVENT.EVENT_DATE) = SEASON.YEAR
        ) T1
    ON (EVENT_RESULT.SEASON_ID = T1.S_ID AND EVENT_RESULT.EVENT_ID = T1.E_ID)
WHEN NOT MATCHED THEN
    INSERT(EVENT_RESULT.SEASON_ID, EVENT_RESULT.EVENT_ID, EVENT_RESULT.DRIVER_ID, EVENT_RESULT.DRIVER_TEAM_ID,
           EVENT_RESULT.START_PLACE, EVENT_RESULT.FINISH_PLACE, EVENT_RESULT.NUM_OF_LAPS, EVENT_RESULT.RACE_TIME,
           EVENT_RESULT.NUM_OF_POINTS, EVENT_RESULT.POLE_POSITION, EVENT_RESULT.WINNER, EVENT_RESULT.TRACK_ID)
    VALUES(T1.S_ID,T1.E_ID,T1.D_ID,T1.TEAM_ID,
           T1.START_DRIVER_PLACE, NULL, T1.LAPS, T1.TIME,
           T1.POINTS, T1.POLE_POSITION, T1.WINNER, T1.TRACK_ID);