INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2019 SEASON', to_date('3/17/2019', 'MM/DD/RRRR'), 'Australian Grand Prix', 'Albert Park Grand Prix Circuit', 'Valtteri Bottas', 'Mercedes', 58, '01:25:27', 26, 2, 'Lewis Hamilton', 'Valtteri Bottas', 7, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2020 SEASON', to_date('3/17/2019', 'MM/DD/RRRR'), 'Australian Grand Prix', 'Albert Park Grand Prix Circuit', 'Lewis Hamilton', 'Mercedes', 58, '20.886', 18, 1, 'Lewis Hamilton', 'Valtteri Bottas', 84, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2021 SEASON', to_date('3/17/2019', 'MM/DD/RRRR'), 'Australian Grand Prix', 'Albert Park Grand Prix Circuit', 'Max Verstappen', 'Red Bull', 58, '22.52', 15, 3, 'Lewis Hamilton', 'Valtteri Bottas', 8, 62);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2022 SEASON', to_date('3/31/2019', 'MM/DD/RRRR'), 'Bahrain Grand Prix', 'Bahrain International Circuit', 'Lewis Hamilton', 'Mercedes', 57, '01:34:21', 25, 3, 'Charles Leclerc', 'Lewis Hamilton', 84, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2023 SEASON', to_date('3/31/2019', 'MM/DD/RRRR'), 'Bahrain Grand Prix', 'Bahrain International Circuit', 'Valtteri Bottas', 'Mercedes', 57, 'Feb-98', 18, 2, 'Charles Leclerc', 'Lewis Hamilton', 7, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2024 SEASON', to_date('3/31/2019', 'MM/DD/RRRR'), 'Bahrain Grand Prix', 'Bahrain International Circuit', 'Charles Leclerc', 'Ferrari', 57, '6.131', 16, 1, 'Charles Leclerc', 'Lewis Hamilton', 2, 239);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2025 SEASON', to_date('4/14/2019', 'MM/DD/RRRR'), 'Chinese Grand Prix', 'Shanghai International Circuit', 'Lewis Hamilton', 'Mercedes', 56, '01:32:06', 26, 1, 'Valtteri Bottas', 'Lewis Hamilton', 84, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2019 SEASON', to_date('4/14/2019', 'MM/DD/RRRR'), 'Chinese Grand Prix', 'Shanghai International Circuit', 'Valtteri Bottas', 'Mercedes', 56, '6.552', 18, 2, 'Valtteri Bottas', 'Lewis Hamilton', 7, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2019 SEASON', to_date('4/14/2019', 'MM/DD/RRRR'), 'Chinese Grand Prix', 'Shanghai International Circuit', 'Sebastian Vettel', 'Ferrari', 56, '13.774', 15, 4, 'Valtteri Bottas', 'Lewis Hamilton', 53, 239);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2019 SEASON', to_date('4/28/2019', 'MM/DD/RRRR'), 'Azerbaijan Grand Prix', 'Baku City Circuit', 'Valtteri Bottas', 'Mercedes', 51, '01:31:52', 26, 2, 'Valtteri Bottas', 'Valtteri Bottas', 7, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2019 SEASON', to_date('4/28/2019', 'MM/DD/RRRR'), 'Azerbaijan Grand Prix', 'Baku City Circuit', 'Lewis Hamilton', 'Mercedes', 51, '1.524', 18, 1, 'Valtteri Bottas', 'Valtteri Bottas', 84, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2019 SEASON', to_date('4/28/2019', 'MM/DD/RRRR'), 'Azerbaijan Grand Prix', 'Baku City Circuit', 'Sebastian Vettel', 'Ferrari', 51, '11.739', 15, 4, 'Valtteri Bottas', 'Valtteri Bottas', 53, 239);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('3/25/2018', 'MM/DD/RRRR'), 'Australian Grand Prix', 'Albert Park Grand Prix Circuit', 'Sebastian Vettel', 'Ferrari', 58, '01:29:33', 25, 3, 'Lewis Hamilton', 'Sebastian Vettel', 53, 239);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('3/25/2018', 'MM/DD/RRRR'), 'Australian Grand Prix', 'Albert Park Grand Prix Circuit', 'Lewis Hamilton', 'Renault', 58, '5.036', 18, 1, 'Lewis Hamilton', 'Sebastian Vettel', 84, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('3/25/2018', 'MM/DD/RRRR'), 'Australian Grand Prix', 'Albert Park Grand Prix Circuit', 'Kimi Räikkönen', 'Ferrari', 58, '6.309', 15, 2, 'Lewis Hamilton', 'Sebastian Vettel', 21, 239);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('08/04/2018', 'MM/DD/RRRR'), 'Bahrain Grand Prix', 'Bahrain International Circuit', 'Sebastian Vettel', 'Ferrari', 57, '01:32:02', 25, 1, 'Sebastian Vettel', 'Sebastian Vettel', 53, 239);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('08/04/2018', 'MM/DD/RRRR'), 'Bahrain Grand Prix', 'Bahrain International Circuit', 'Valtteri Bottas', 'Mercedes', 57, '0.699', 18, 3, 'Sebastian Vettel', 'Sebastian Vettel', 7, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('08/04/2018', 'MM/DD/RRRR'), 'Bahrain Grand Prix', 'Bahrain International Circuit', 'Lewis Hamilton', 'Renault', 57, '6.512', 15, 4, 'Sebastian Vettel', 'Sebastian Vettel', 84, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('4/15/2018', 'MM/DD/RRRR'), 'Chinese Grand Prix', 'Shanghai International Circuit', 'Daniel Ricciardo', 'Red Bull', 56, '01:35:36', 25, 2, 'Sebastian Vettel', 'Daniel Ricciardo', 7, 62);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('4/15/2018', 'MM/DD/RRRR'), 'Chinese Grand Prix', 'Shanghai International Circuit', 'Valtteri Bottas', 'Mercedes', 56, '8.894', 18, 1, 'Sebastian Vettel', 'Daniel Ricciardo', 7, 102);
INSERT INTO DATA_TABLE (SEASON, EVENT_DATE, EVENT, CIRCUIT, DRIVER, CONSTRUCTOR, LAPS, TIME, POINTS, START_DRIVER_PLACE, POLE_POSITION, WINNER, DRIVER_WINS, CONSTRUCTOR_WINS) 
VALUES ('2018 SEASON', to_date('4/15/2018', 'MM/DD/RRRR'), 'Chinese Grand Prix', 'Shanghai International Circuit', 'Kimi Räikkönen', 'Ferrari', 56, '9.637', 15, 3, 'Sebastian Vettel', 'Daniel Ricciardo', 21, 239);
