--view
SELECT 
    SEASON.NAME SEASON_NAME,
    EVENT.EVENT_DATE EVENT_DATE,
    EVENT.NAME EVENT_NAME,
    TRACK.NAME TRACK_NAME,
    DRIVER.NAME DRIVER_NAME,
    TEAM.NAME TEAM_NAME,
    EVENT_RESULT.NUM_OF_LAPS LAPS,
    EVENT_RESULT.RACE_TIME RACE_TIME,
    EVENT_RESULT.NUM_OF_POINTS POINTS,
    EVENT_RESULT.START_PLACE START_PLACE,
    EVENT_RESULT.POLE_POSITION POLE_POSITION,
    EVENT_RESULT.WINNER WINNER,
    DRIVER_STATISTIC.EVENT_WINS DRIVER_WINS,
    TEAM_STATISTIC.NUM_OF_WINS CONSTRUCTOR_WINS
FROM SEASON
LEFT JOIN SEASON_EVENT
    ON SEASON.ID = SEASON_EVENT.SEASON_ID
LEFT JOIN EVENT
    ON SEASON_EVENT.EVENT_ID = EVENT.ID
LEFT JOIN TRACK
    ON SEASON_EVENT.TRACK_ID = TRACK.ID
RIGHT JOIN EVENT_RESULT
    ON SEASON_EVENT.SEASON_ID = EVENT_RESULT.SEASON_ID AND SEASON_EVENT.EVENT_ID = EVENT_RESULT.EVENT_ID
LEFT JOIN DRIVER
    ON EVENT_RESULT.DRIVER_ID = DRIVER.ID
LEFT JOIN TEAM
    ON EVENT_RESULT.DRIVER_TEAM_ID = TEAM.ID
LEFT JOIN DRIVER_STATISTIC
    ON DRIVER.ID = DRIVER_STATISTIC.DRIVER_ID AND SEASON.ID = DRIVER_STATISTIC.SEASON_ID
LEFT JOIN TEAM_STATISTIC
    ON TEAM.ID = TEAM_STATISTIC.TEAM_ID AND SEASON.ID = TEAM_STATISTIC.SEASON_ID
ORDER BY SEASON.ID DESC, EVENT.EVENT_DATE ASC, EVENT_RESULT.NUM_OF_POINTS DESC; 
    
