DEFINE USER_NAME = &&1
DEFINE DATA_name = '&&USER_NAME._DATA'
DEFINE IDX_name = '&&USER_NAME._IDX'

DROP TABLESPACE &&DATA_name
    INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
PROMPT "TBS .DATA dropped"

DROP TABLESPACE &&IDX_name
    INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
PROMPT "TBS .IDX dropped"

UNDEFINE USER_NAME
UNDEFINE DATA_name
UNDEFINE IDX_name